### ISSUE TITLE
Adicionar algumas referências

### ISSUE THREAD

**Issue by woliveiras** [tapmorales/workflow-front-end#3]
@tapmorales excelente iniciativa!

Curti bastante sua ideia de falar sobre as mudanças na área de front end!

Eu levantei uns links para falar sobre essas mudanças de mercado quando fiz essa palestra: [JavaScript e o perfil do desenvolvedor front end das atualidades mais atuais](http://pt.slideshare.net/williamoliveira542/javascript-e-o-perfil-do-desenvolvedor-front-end-das-atualidades-mais-atuais-60080893)

E pra montar o [Carreira Front End](https://github.com/woliveiras/front-end-career)

Seria interessante colocar alguns links relacionados para quem quiser se aprofundar mais ainda nos assuntos que você falou nos capítulos. Você daria um direcionamento para quem lê o seu conteúdo continuar estudando com fontes que você confia. :)

Parabéns pelo projeto.

**Comment by tapmorales** [comment]
Ola. Obrigado pelo feedback.

Curti bastante os links que voce passou. Quando der um tempinho vou criar uma página contendo estes e outros links interessantes. Boa ideia.

Abração

Daniel
